# Categorical data
* Nominal Data
    * 남자 / 여자 
* Ordinal Data
    * 좋다 / 보통 / 싫다 --> 3, 2, 1 

## Categorical --> Numerical
* https://teddylee777.github.io/scikit-learn/labelencoder-%EC%82%AC%EC%9A%A9%EB%B2%95
* from sklearn.preprocessing import OneHotEncoder
* from sklearn.preprocessing import LabelEncoder
* pd.get_dummies()
* cat.codes

### 1. pd.get_dummies()

* Ordinal 변수는 숫자로 인식해서 범주형 처리를 하지 않음 (원핫인코더와의 큰 차이)

* (단점) 테스트셋에 새로운 데이터가 들어왔을 때 에러를 내뱉음

### 2. OneHotEncoder

* 원핫인코더의 좋은 점은 Ordinal 변수도 모두 범주형으로 인식하여 처리

* (단점) 테스트셋에 새로운 데이터가 들어왔을 때 에러를 내뱉음

### 3. cat.codes

* 어떤 클래스가 숫자로 맵핑되어 있느지 확인하기 어려움

## 예시

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [3]:
train = pd.read_csv('/home/hanhs/ML_DA_study/house_prices/data/base_data/train.csv')

In [4]:
train['MSZoning'].unique()

array(['RL', 'RM', 'C (all)', 'FV', 'RH'], dtype=object)

## 1) cat.codes

In [5]:
a = train['MSZoning'].astype('category').cat.codes

In [6]:
a.head(3)

0    3
1    3
2    3
dtype: int8

In [7]:
a.unique()

array([3, 4, 0, 1, 2], dtype=int8)

## 2) LabelEncoder

In [8]:
le = LabelEncoder()

In [9]:
b = le.fit_transform(train['MSZoning'])

In [10]:
b

array([3, 3, 3, ..., 3, 3, 3])

In [11]:
np.unique(b)

array([0, 1, 2, 3, 4])

## 3) get_dummies()

In [13]:
pd.get_dummies(train['MSZoning']).head()

C (all)  FV  RH  RL  RM
0        0   0   0   1   0
1        0   0   0   1   0
2        0   0   0   1   0
3        0   0   0   1   0
4        0   0   0   1   0